### PR TITLE
borders in the sideBarSections and terminal split more visible

### PR DESCRIPTION
**Pull request by NorfeldtAbtion**
This is the solution for #31 

Screenshot 2022-01-05 at 10 03 01

Sorry for the formatting of some lines, it was done automatically.

### CODE REVIEW

**Review by atomiks — COMMENTED** [review]
I think these changes should be applied to Moonlight II, not Moonlight?

**Comment by NorfeldtAbtion** [comment]
I'm not using version II, so did not know how much I should change

**Comment by atomiks** [comment]
Ah okay, you could probably apply those two lines to Moonlight II as well, so both versions have better borders

**Comment by NorfeldtAbtion** [comment]
I'll do that

**Comment by NorfeldtAbtion** [comment]
done 👍 @atomiks

**Comment by atomiks** [comment]
Thanks!

**Pull request merged**
