### PR TITLE
Updated Readme with better guidelines and more info, plus added a draft for contribution info

### PR DESCRIPTION
**Pull request by nfuad**
## Updated Readme.md
1. Added detailed methods of installation
2. Added details for activation
3. Updated Description
4. Added Icons
5. Added contributor section

## Added Contributing.md
1. Created a draft file for contributors.

*NOTE: Please review the links properly and test the steps out if possible.*

### CODE REVIEW

**Comment by atomiks** [comment]
Thanks for the PR!

> Moonlight Theme is the most amazing Visual Studio Code theme

😮 don't know about this part lol

**Comment by nfuad** [comment]
> Moonlight Theme is the most amazing Visual Studio Code theme

Haha, I got a bit over ambitious maybe :sweat_smile: 
We can just do "Moonlight Theme is an amazing Visual Studio Code theme" if you want.

**Comment by atomiks** [comment]
I don't think we need a tagline like that, the preview image should speak for itself if a visitor likes it. After all themes are mostly subjective. Everything else looks good though, I'd just remove the lines above "Getting Started".

**Comment by nfuad** [comment]
Ok. I don't have any problem with that.

**Pull request closed without merging**
